name: Docker API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-backend-app .

    - name: Run container
      run: docker run -d -p 5000:5000 --name my-app my-backend-app

    - name: Wait for app to start
      run: sleep 5

    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq

    - name: Test /registration
      run: |
        curl -X POST http://localhost:5000/registration \
          -H "Content-Type: application/json" \
          -d '{"username":"X","password":"abc123"}'

    - name: Test /login
      id: login
      run: |
        response=$(curl -s -X POST http://localhost:5000/login \
          -H "Content-Type: application/json" \
          -d '{"username":"X","password":"abc123"}')
        echo "$response"
        token=$(echo "$response" | jq -r '.access_token')
        echo "TOKEN=$token" >> $GITHUB_ENV

    - name: Test /predict
      run: |
        curl -X POST http://localhost:5000/predict \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d '{
            "longitude": -122.64,
            "latitude": 38.01,
            "housing_median_age": 36.0,
            "total_rooms": 1336.0,
            "total_bedrooms": 258.0,
            "population": 678.0,
            "households": 249.0,
            "median_income": 5.5789,
            "ocean_proximity": "NEAR OCEAN"
          }'

    - name: Stop container
      run: docker rm -f my-app
