name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r housing_prices_dashboard/requirements.txt

      - name: Run tests
        run: pytest
        env:
          MODEL_PATH: './housing_prices_dashboard/model.joblib'
          HOST: "127.0.0.1"
          PORT: "5000"
          DATABASE_URL: "sqlite:///./users.db"
          DATA_PATH: './housing_prices_dashboard/housing.csv'
          SECRET_KEY: "SuperSecretKey"
          ALGORITHM: "HS256"
          ISSUER: "http://127.0.0.1:5000"
          AUDIENCE: "FastAPI"
